// OBLIVIOUS HUB — password prompt preload.
//
// Exposes a single, narrow API to the password dialog: submit(channel, value).
// No other IPC, no Node, no fs.  The dynamic channel name is generated by the
// main process per prompt and cannot be guessed by the page.

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("secboot", {
  submit: (channel, value) => {
    if (typeof channel !== "string") return Promise.reject(new Error("bad_channel"));
    if (!/^secboot:submit:[a-z0-9]+:[a-z0-9]+$/.test(channel)) {
      return Promise.reject(new Error("invalid_channel"));
    }
    return ipcRenderer.invoke(channel, String(value || ""));
  },
});
